CREATE TABLE FG_TABLE
(
    ID            BIGINT       NOT NULL COMMENT '表主键',
    PROJECT_ID    BIGINT       NOT NULL COMMENT '项目主键',
    NAME          VARCHAR(255) NOT NULL COMMENT '表名',
    COMMENT       VARCHAR(255) COMMENT '表描述',
    CLASS_NAME    VARCHAR(255) NOT NULL COMMENT 'Java类名',
    ROOT_PACKAGE  VARCHAR(255) NOT NULL COMMENT 'Java包',
    MODULE_NAME   VARCHAR(255) NOT NULL COMMENT '模块名',
    BUSINESS_NAME VARCHAR(255) NOT NULL COMMENT '业务名',
    AUTHOR        VARCHAR(255) COMMENT '作者',
    CONSTRAINT FG_TABLE_PK PRIMARY KEY (ID)
);

CREATE TABLE FG_TABLE_COLUMN
(
    ID          BIGINT       NOT NULL COMMENT '字段主键',
    PROJECT_ID  BIGINT       NOT NULL COMMENT '项目主键',
    TABLE_ID    BIGINT       NOT NULL COMMENT '表主键',
    NAME        VARCHAR(255) NOT NULL COMMENT '字段名',
    COMMENT     VARCHAR(255) COMMENT '字段描述',
    TYPE        VARCHAR(255) NOT NULL COMMENT '字段类型',
    PK          BOOLEAN DEFAULT FALSE COMMENT '主键',
    INCREMENT   BOOLEAN DEFAULT FALSE COMMENT '自增',
    NULLABLE    BOOLEAN DEFAULT TRUE COMMENT '空',
    SIZE        INT COMMENT '大小',
    digit       INT COMMENT '数据长度',
    SORT        INT COMMENT '排序',
    REQUIRED    BOOLEAN DEFAULT FALSE COMMENT '必填',
    CAN_INSERT  BOOLEAN DEFAULT TRUE COMMENT '插入',
    CAN_UPDATE  BOOLEAN DEFAULT TRUE COMMENT '更新',
    CAN_LIST    BOOLEAN DEFAULT TRUE COMMENT '列表',
    CAN_SELECT  BOOLEAN DEFAULT TRUE COMMENT '查询',
    SELECT_TYPE VARCHAR(255) COMMENT '查询方式',
    JAVA_NAME   VARCHAR(500) COMMENT 'java字段名',
    JAVA_TYPE   VARCHAR(500) COMMENT 'java类型',
    HTML_TYPE   VARCHAR(500) COMMENT 'html类型',
    DICT_TYPE   VARCHAR(500) COMMENT '字典类型',
    CONSTRAINT FG_TABLE_COLUMN_PK PRIMARY KEY (ID)
);