CREATE TABLE FG_PROJECT
(
    ID   BIGINT       NOT NULL COMMENT '主键',
    NAME VARCHAR(255) NOT NULL COMMENT '项目名称',
    CONSTRAINT FG_PROJECT_PK PRIMARY KEY (ID),
    CONSTRAINT FG_PROJECT_UN UNIQUE (NAME)
);

CREATE TABLE FG_PROJECT_SETTING
(
    ID                   BIGINT       NOT NULL COMMENT '主键',
    PROJECT_ID           BIGINT       NOT NULL COMMENT '项目主键',
    DB_INFO_ID           BIGINT       NOT NULL COMMENT '数据主键',
    TEMP_PATH            VARCHAR(500) NOT NULL COMMENT '模版路径',
    ROOT_PACKAGE         VARCHAR(255) NOT NULL COMMENT 'java包',
    AUTHOR               VARCHAR(255) NOT NULL COMMENT '作者',
    IGNORE_TABLE_PREFIX  VARCHAR(255) COMMENT '忽略表前缀',
    IGNORE_COLUMN        VARCHAR(500) COMMENT '忽略表字段',
    IGNORE_INSERT_COLUMN VARCHAR(500) COMMENT '忽略插入字段',
    IGNORE_SELECT_COLUMN VARCHAR(500) COMMENT '忽略查询字段',
    DICT_USE             BOOLEAN DEFAULT FALSE COMMENT '是否开启字典表查询',
    DICT_SQL             VARCHAR(2000) COMMENT '字典表查询sql',
    CONSTRAINT FG_PROJECT_SETTING_PK PRIMARY KEY (ID),
    CONSTRAINT FG_PROJECT_SETTING_UN UNIQUE (PROJECT_ID)
);