CREATE TABLE FG_TYPE
(
    ID     BIGINT       NOT NULL COMMENT '主键',
    MOLD   VARCHAR(32)  NOT NULL COMMENT '类型 DB,HTML,JAVA,SELECT',
    NAME   VARCHAR(64)  NOT NULL COMMENT '描述',
    VAL    VARCHAR(64)  NOT NULL COMMENT '值',
    DIS    BOOLEAN      NOT NULL DEFAULT FALSE COMMENT '禁用',
    REMARK VARCHAR(255) NOT NULL DEFAULT FALSE COMMENT '描述',
    CONSTRAINT FG_TYPE_PK PRIMARY KEY (ID),
    UNIQUE INDEX FG_TYPE_UI0 (MOLD, VAL)
);

CREATE TABLE FG_TYPE_MAP
(
    ID        BIGINT       NOT NULL COMMENT '主键',
    TYPE_ID   BIGINT       NOT NULL COMMENT '类型主键',
    TYPE_MOLD VARCHAR(255) NOT NULL COMMENT '类型的类型 DB,HTML,JAVA,SELECT',
    MAP_ID    BIGINT       NOT NULL COMMENT '映射主键',
    MAP_MOLD  VARCHAR(255) NOT NULL COMMENT '映射的类型 DB,HTML,JAVA,SELECT',
    CONSTRAINT FG_TYPE_MAP_PK PRIMARY KEY (ID),
    UNIQUE INDEX FG_TYPE_MAP_UI0 (TYPE_MOLD, MAP_MOLD, TYPE_ID)
);