ALTER TABLE F_TABLE
    -- drop
    DROP COLUMN ROOT_PACKAGE,
    DROP COLUMN BUSINESS_NAME,
    DROP COLUMN AUTHOR,
    DROP COLUMN CLASS_NAME,
    DROP COLUMN MODULE_NAME,
    -- add
    ADD COLUMN CAMEL varchar(255) NULL COMMENT '小驼峰 tableName',
    ADD COLUMN UP_CAMEL varchar(255) NULL COMMENT '大驼峰 TableName',
    ADD COLUMN UNDERLINE varchar(255) NULL COMMENT '小下划线 table_name',
    ADD COLUMN UP_UNDERLINE varchar(255) NULL COMMENT '大下划线 TABLE_NAME',
    ADD COLUMN `MODULE` varchar(255) NULL COMMENT '模块名';

ALTER TABLE F_SETS DROP COLUMN ROOT_PACKAGE,
    -- drop
    DROP COLUMN IGNORE_TABLE_PREFIX,
    DROP COLUMN IGNORE_COLUMN,
    DROP COLUMN IGNORE_INSERT_COLUMN,
    DROP COLUMN IGNORE_SELECT_COLUMN,
    -- add
    ADD COLUMN PKG varchar(255) NULL COMMENT '文件(包)';

ALTER TABLE F_COLUMN DROP COLUMN CAN_INSERT,
    -- drop
    DROP COLUMN CAN_UPDATE,
    DROP COLUMN CAN_LIST,
    DROP COLUMN CAN_SELECT,
    DROP COLUMN SELECT_TYPE,
    DROP COLUMN JAVA_NAME,
    DROP COLUMN JAVA_TYPE,
    DROP COLUMN HTML_TYPE,
    -- add
    ADD COLUMN CAMEL varchar(255) NULL COMMENT '小驼峰 tableName',
    ADD COLUMN UP_CAMEL varchar(255) NULL COMMENT '大驼峰 TableName',
    ADD COLUMN UNDERLINE varchar(255) NULL COMMENT '小下划线 table_name',
    ADD COLUMN UP_UNDERLINE varchar(255) NULL COMMENT '大下划线 TABLE_NAME',
    ADD COLUMN TYPES varchar(4000) NULL COMMENT '类型JSON';

