ALTER TABLE FG_DATABASE_INFO RENAME TO F_DB_INFO;
ALTER TABLE FG_PROJECT RENAME TO F_PROJ;
ALTER TABLE FG_PROJECT_SETTING RENAME TO F_SETS;
ALTER TABLE FG_TABLE RENAME TO F_TABLE;
ALTER TABLE FG_TABLE_COLUMN RENAME TO F_COLUMN;
ALTER TABLE FG_TYPE RENAME TO F_TYPE;
ALTER TABLE FG_TYPE_MAP RENAME TO F_TYPE_MAP;