CREATE TABLE F_CONFIG
(
    ID     BIGINT       NOT NULL COMMENT '主键',
    `TYPE` VARCHAR(255) NOT NULL COMMENT '类型',
    NAME   VARCHAR(255) NOT NULL COMMENT '名称',
    `KEY`  VARCHAR(255) NOT NULL COMMENT '键',
    VAL    VARCHAR(255) NOT NULL COMMENT '值',
    REMARK VARCHAR(2000) COMMENT '描述',
    CONSTRAINT F_CONFIG_PK PRIMARY KEY (ID),
    CONSTRAINT F_CONFIG_PK_UN UNIQUE (`TYPE`,`KEY`)
);